app:
  readTimeout: 5s
  shutdownTimeout: 5s
  writeTimeout: 5s
db:
  uri: file:indahaus.db?_busy_timeout=5000
port: 8080
auth:
  username: "*****"
  password: "*****"
debugPort: 4000
version:
  build: develop
