apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DB_URI
            valueFrom:
              configMapKeyRef:
                name: {{ include "helm.fullname" . }}-config
                key: db-uri
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "helm.fullname" . }}-secret
                key: auth-password
          - name: AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "helm.fullname" . }}-secret
                key: auth-username
          - name: PORT
            value: {{ .Values.port | default 8080 | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
            - name: debug
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
