apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secret
  labels:
  {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth-username: {{ .Values.auth.username | b64enc | quote }}
  auth-password: {{ .Values.auth.password | b64enc | quote }}
  db-username: {{ .Values.db.username | b64enc | quote }}
  db-password: {{ .Values.db.password | b64enc | quote }}
